// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoAdd: typeof import('./src/components/TodoAdd.vue')['default']
    TodoFilter: typeof import('./src/components/TodoFilter.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
    TodoListItem: typeof import('./src/components/TodoListItem.vue')['default']
  }
}
